### ISSUE TITLE
Set minimum required version of Mojolicious

### ISSUE THREAD

**Issue by reneeb** [jhthorsen/mojolicious-plugin-cgi#13]
You're using Mojo::IOLoop->reset in your code (https://github.com/jhthorsen/mojolicious-plugin-cgi/blob/master/lib/Mojolicious/Plugin/CGI.pm#L206). That method was added in Mojolicious 5.08, but you do not declare a minimum required version in your Makefile.PL

**Comment by jhthorsen** [comment]
Thank you!

Had a typo on the cpanfile I use to generate Makefile.PL
