### ISSUE TITLE
Can't call method "write" on an undefined value at ... Mojo/Server/Daemon.pm line 224

### ISSUE THREAD

**Issue by leejo** [jhthorsen/mojolicious-plugin-cgi#16]
We're seeing the above error a lot in our mojo logs, and having bisected it i've discovered the offending commit is d6794c806202546090abffeedb39bcae72ef77d7. I'm not sure if this is down to our configuration (AWS ELB -> Apache -> Hypnotoad) and the only way i can replicate it is by banging on the refresh/stop button in a browser (so this is perhaps a load issue?). Here's the (slightly censored) log entires from mojo when i do so.

Single request:

```
[Tue May 26 12:45:47 2015] [debug] GET "/"
[Tue May 26 12:45:47 2015] [debug] Routing to a callback
[Tue May 26 12:45:47 2015] [debug] [CGI:giga.cgi:3738] START .../cgi-bin/giga.cgi
[Tue May 26 12:45:47 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:45:50 2015] [debug] 200 OK (3.278485s, 0.305/s)
````

Rapidly hitting the stop/refresh button in the browser:

```
[Tue May 26 12:49:35 2015] [debug] GET "/"
[Tue May 26 12:49:35 2015] [debug] Routing to a callback
[Tue May 26 12:49:35 2015] [debug] [CGI:giga.cgi:3740] START .../cgi-bin/giga.cgi
[Tue May 26 12:49:35 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:49:35 2015] [debug] GET "/"
[Tue May 26 12:49:35 2015] [debug] Routing to a callback
[Tue May 26 12:49:35 2015] [debug] [CGI:giga.cgi:3741] START .../cgi-bin/giga.cgi
[Tue May 26 12:49:35 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:49:35 2015] [debug] 200 OK (0.416469s, 2.401/s)
[Tue May 26 12:49:35 2015] [debug] GET "/"
[Tue May 26 12:49:35 2015] [debug] Routing to a callback
[Tue May 26 12:49:35 2015] [debug] [CGI:giga.cgi:3743] START .../cgi-bin/giga.cgi
[Tue May 26 12:49:35 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:49:35 2015] [debug] 200 OK (0.402992s, 2.481/s)
[Tue May 26 12:49:35 2015] [error] Can't call method "write" on an undefined value at .../Mojo/Server/Daemon.pm line 224.

[Tue May 26 12:49:36 2015] [debug] GET "/"
[Tue May 26 12:49:36 2015] [debug] Routing to a callback
[Tue May 26 12:49:36 2015] [debug] [CGI:giga.cgi:3744] START .../cgi-bin/giga.cgi
[Tue May 26 12:49:36 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:49:36 2015] [debug] 200 OK (0.699041s, 1.431/s)
[Tue May 26 12:49:36 2015] [error] Can't call method "write" on an undefined value at .../Mojo/Server/Daemon.pm line 224.

[Tue May 26 12:49:36 2015] [debug] 200 OK (1.165548s, 0.858/s)
[Tue May 26 12:49:36 2015] [debug] GET "/"
[Tue May 26 12:49:36 2015] [debug] Routing to a callback
[Tue May 26 12:49:36 2015] [debug] [CGI:giga.cgi:3746] START .../cgi-bin/giga.cgi
[Tue May 26 12:49:36 2015] [debug] Nothing has been rendered, expecting delayed response
[Tue May 26 12:49:36 2015] [debug] 200 OK (0.710926s, 1.407/s)
[Tue May 26 12:49:36 2015] [debug] 200 OK (1.383800s, 0.723/s)
[Tue May 26 12:49:36 2015] [debug] 200 OK (1.063482s, 0.940/s)
[Tue May 26 12:49:36 2015] [error] Can't call method "write" on an undefined value at .../Mojo/Server/Daemon.pm line 224.

[Tue May 26 12:49:36 2015] [debug] 200 OK (1.092113s, 0.916/s)
[Tue May 26 12:49:36 2015] [debug] 200 OK (1.761754s, 0.568/s)
[Tue May 26 12:49:36 2015] [error] Can't call method "write" on an undefined value at .../Mojo/Server/Daemon.pm line 224.

[Tue May 26 12:49:36 2015] [debug] 200 OK (0.831375s, 1.203/s)
[Tue May 26 12:49:39 2015] [debug] 200 OK (4.369726s, 0.229/s)
[Tue May 26 12:49:40 2015] [debug] 200 OK (4.731871s, 0.211/s)
[Tue May 26 12:49:40 2015] [debug] 200 OK (5.189997s, 0.193/s)
[Tue May 26 12:49:41 2015] [debug] 200 OK (5.055516s, 0.198/s)
[Tue May 26 12:49:41 2015] [debug] 200 OK (4.893447s, 0.204/s)
```

That was running under morbo, we see the same under hypnotoad although the capacity is greater before the errors start appearing. Any clues? Could do with some advice here, even if it's "don't do that".

Latest version of Mojolicious::Plugin::CGI and:

```
> perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
```

```
> pmvers Mojolicious
6.10
```

**Comment by leejo** [comment]
Managed to replicate this in a test case: https://github.com/leejo/mojolicious-plugin-cgi/commit/1998e78f1efad25d111bffdf6c2da6f286207e2a

**Comment by leejo** [comment]
Note if i comment out the Mojo::IOLoop->reset line the test passes with no warnings - so i don't know if/what value the ->reset call adds (although is a little over my head so am more than likely not understanding the rationale for it).

**Comment by jhthorsen** [comment]
```Mojo::IOLoop->reset``` makes sure the child CGI process can't continue the running the loop. Further explanation: On fork(), the child duplicates all the watched filehandles, recurring timers, +++ that is already defined in the Mojo::Reactor. This means that nasty/unexpected things can happen in the child if it decides to do ```Mojo::IOLoop->start```. A CGI script will probably not do that directly, but it might use a module from CPAN which starts the IOLoop or use EV.

**Comment by jhthorsen** [comment]
Sorry for the late response. I've forgotten about this issue :disappointed:

Will try to make a test case for it now.

**Comment by jhthorsen** [comment]
That was pretty stupid... The module does exec(), so there's no need to reset the IOLoop.

**Comment by jhthorsen** [comment]
Thanks for the test @leejo :+1:

**Comment by leejo** [comment]
No problem, thanks for explaining the rationale behind the original implementation.

Envoyé par myMail pour iOS


dimanche, 12 juillet 2015 15:26 +0200 de Jan Henning Thorsen  <notifications@github.com>:
