### ISSUE TITLE
Passing env variables broken in current version

### ISSUE THREAD

**Issue by aptituz** [jhthorsen/mojolicious-plugin-cgi#19]
Hi,

the documentation says that %ENV is being passed as the (default) environment to the CGIs, which were true for at least version 0.26 but doesn't work in the current released version. Maybe this is a (unwanted) side-effect of the change that shall call cgis with env in tests?

Greetings,
Patrick

**Comment by jhthorsen** [comment]
Could you provide a failing test? Or an example where %ENV is not passed to the script.

**Comment by aptituz** [comment]
It's internal software where it happened (and downgrading solved the issue) but if I find time I'll see if I can reproduce it with a minimal test case. In my case it were the PERL5LIB var which wasn't passed to the CGIs, thus not finding custom libs.

**Comment by jhthorsen** [comment]
I will create a fix when you provide a failing case.

**Comment by aptituz** [comment]
So here it is: https://gist.github.com/aptituz/71d53cc25ae27d11300c711d8ff3d7b5

Note that FooBar.pm needs to be in a subdirectory lib. You will see it failing by moaning about being unable to find FooBar.pm in @INC. And in fact the lib directory added via %ENV is missing. The very same testcase worked before upgrading the module:

Successfully installed Mojolicious-Plugin-CGI-0.31 (upgraded from 0.26)

By the way, I'm now unable to downgrade to that version, because it's not on cpan anymore. Have you unpublished it?

**Comment by jhthorsen** [comment]
I delete old versions as I release a new version. You can install it from github though:

    cpanm https://github.com/jhthorsen/mojolicious-plugin-cgi/archive/0.26.tar.gz

Just change "0.26" with whatever version you want.

**Comment by jhthorsen** [comment]
Thanks for your input! 👍 

Hope the new version works as expected.

**Comment by aptituz** [comment]
Thanks for the quick solution.

Will try to verify it ASAP, but probably won't make it today.

Am Sonntag, 17. April 2016 schrieb Jan Henning Thorsen :

**Comment by aptituz** [comment]
Although you already relased a fixed version and closed the issue, I still want to give you the promised feedback: Works fine with the new version. Thank you very much.

**Comment by jhthorsen** [comment]
Thanks for your feedback! I appreciate it 👍
