### ISSUE TITLE
Fails with Mojolicious 8.06

### ISSUE THREAD

**Issue by andk** [jhthorsen/mojolicious-plugin-cgi#30]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/d1e8eeac-eb1f-11e8-8bc9-d5a903258b13

**Comment by bimmerlabs** [comment]
It's currently crashing perl.exe during the tests.

Not sure if it's related to this issue or not - running Strawberry Perl 5.28.01 (64 bit), Mojolicious 8.09. 

build.log attached.
[build.log](https://github.com/jhthorsen/mojolicious-plugin-cgi/files/2680797/build.log)

**Comment by jhthorsen** [comment]
@bimmerlabs: I don't know how to fix Windows issues. And I'm 99.9% sure it' not related to this issue.

Google answered this though: https://support.microsoft.com/en-us/help/884538/you-receive-a-this-application-has-requested-the-runtime-to-terminate

Please open a new issue if you think there's a problem with M::P::CGI.
